name: CD Staging

on:
  push:
    branches: [staging]

jobs:
  deploy-staging:
    name: Build & Deploy to Staging Cluster
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Core API Container
        uses: docker/build-push-action@v5
        with:
          context: ./services/core-api
          file: ./services/core-api/Dockerfile
          target: runtime
          push: false
          tags: flip/core-api:staging

      - name: Build Web PWA Container
        uses: docker/build-push-action@v5
        with:
          context: ./apps/web
          file: ./apps/web/Dockerfile
          target: production
          push: false
          tags: flip/web:staging
